export const CHANGE_SECONDS = "CHANGE_SECONDS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const INCREMENT_SECONDS_PER_PAGE = "INCREMENT_SECONDS";
export const DECREMENT_SECONDS_TIMER = "CHANGE_SECONDS_TIMER";
export const RESET_SECONDS_TIMER = "RESET_SECONDS_TIMER";
export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const TOGGLE_TIMER_STATE = "TOGGLE_TIMER_STATE";
